# Generated by Django 3.2.14 on 2023-03-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_fischpictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='media/events/', verbose_name='Pictures'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fischpictures',
            name='image',
            field=models.ImageField(null=True, upload_to='media/fisch_pictures/', verbose_name='Pictures'),
        ),
    ]
