# Generated by Django 3.2.14 on 2023-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_fischpictures_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='black_sponsor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='bronze_sponsor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='diamond_sponsor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gold_sponsor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/', verbose_name='Pictures'),
        ),
        migrations.AddField(
            model_name='profile',
            name='silver_sponsor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sponsor_score',
            field=models.IntegerField(default=0),
        ),
    ]
