# Generated by Django 3.2.14 on 2023-03-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20230327_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='fischpictures',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fischpictures',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
