# Generated by Django 3.2.14 on 2023-03-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20230328_1136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FischPictures',
            new_name='FischPicture',
        ),
    ]
