# Generated by Django 3.2.3 on 2023-03-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_profile_image'),
        ('pages', '0012_rename_fischpictures_fischpicture'),
    ]

    operations = [
    ]
