# Generated by Django 3.2.3 on 2023-04-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_merge_20230330_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/', verbose_name='Pictures'),
        ),
    ]
