# Generated by Django 3.2.14 on 2023-04-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattlePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='battlepass/', verbose_name='Pictures')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('max_donation', models.IntegerField(default=300)),
                ('items', models.ManyToManyField(related_name='items', through='pages.BattlePass', to='pages.SeasonItem')),
            ],
        ),
        migrations.AddField(
            model_name='battlepass',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.seasonitem'),
        ),
        migrations.AddField(
            model_name='battlepass',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.season'),
        ),
    ]
