# Generated by Django 3.2.14 on 2023-04-18 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20230416_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='items',
        ),
        migrations.AddField(
            model_name='season',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='battlepass/', verbose_name='Pictures'),
        ),
        migrations.AddField(
            model_name='seasonitem',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pages.season'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='season_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='unlocked_items',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
