# Generated by Django 3.2.14 on 2023-04-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20230418_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sponsor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.sponsor'),
        ),
        migrations.DeleteModel(
            name='BattlePass',
        ),
    ]
