# Generated by Django 3.2.14 on 2023-04-18 20:42

from django.db import migrations, models
from ..models import Sponsor,Profile

def add_sponsors(apps, schema_editor):
    Sponsor.objects.bulk_create([Sponsor() for i in Profile.objects.values_list("id", flat=True)], ignore_conflicts=True)
    sponsors = Sponsor.objects.all()
    users = Profile.objects.all()
    for sponsor,user in zip(sponsors,users):
        user.sponsor_id = sponsor.id
        user.save()
        sponsor.first_name = user.first_name
        sponsor.last_name = user.last_name
        sponsor.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20230418_2241'),
    ]

    operations = [migrations.AddField(
            model_name='sponsor',
            name='unlocked_items_animation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RunPython(add_sponsors)
    ]
