# Generated by Django 3.2.14 on 2023-04-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20230418_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.sponsor'),
        ),
    ]
