# Generated by Django 3.2.14 on 2023-04-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_profile_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='unlocked_items_animation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
