# Generated by Django 3.2.14 on 2023-05-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20230508_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='worldmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Pictures'),
        ),
    ]
