# Generated by Django 3.2.14 on 2023-05-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_event_worldmap_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='season_score',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
