# Generated by Django 3.2.14 on 2023-05-19 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_sponsor_season_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50)),
                ('food', models.CharField(blank=True, max_length=200)),
                ('drinks', models.CharField(blank=True, max_length=200)),
                ('comments', models.CharField(blank=True, max_length=400)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='Pictures')),
                ('comments', models.CharField(blank=True, max_length=400)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProposalLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('item_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='pages.itemproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_proposal_likes', to='pages.profile')),
            ],
        ),
        migrations.CreateModel(
            name='EventProposalLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('event_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='pages.eventproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_proposal_likes', to='pages.profile')),
            ],
        ),
    ]
