# Generated by Django 3.2.14 on 2023-05-21 15:19

from django.db import migrations, models
from ..models import Sponsor,Profile
from django.contrib.auth.models import User

def add_sponsor_username(apps, schema_editor):
    sponsors = Sponsor.objects.all()
    for sponsor in sponsors:
        sponsor.username = User.objects.get(id=Profile.objects.get(sponsor_id=sponsor.id).user_id).username
        sponsor.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_eventproposal_eventproposallikes_itemproposal_itemproposallikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(add_sponsor_username)
    ]
