# Generated by Django 4.2.3 on 2023-09-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_sponsor_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
