# Generated by Django 4.2.3 on 2023-12-15 08:31

from django.db import migrations, models
import django.db.models.deletion
from ..models import *

def add_user_token(apps, schema_editor):
    profiles = Profile.objects.all()
    for profile in profiles:
        token = ExpoToken.objects.create()
        profile.expo_token = token
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_fischpicturelikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='expo_token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.expotoken'),
        ),
        migrations.RunPython(add_user_token)
    ]
