# Generated by Django 4.2.3 on 2024-01-29 06:30

from django.db import migrations, models
from ..models import Sponsor,Season,SeasonBadge
def add_season_badges(apps, schema_editor):
    sponsors = Sponsor.objects.all()
    season = Season.objects.last()
    season_badge = SeasonBadge.objects.create(season_badge=season.image)  # season.image.path.split('media')[1]
    season_badge.save()
    for sponsor in sponsors:
        if sponsor.season_score >= season.max_donation:
            sponsor.season_badges.add(season_badge)
            sponsor.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_expotoken_profile_expo_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('update', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_badge', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='season_badges',
            field=models.ManyToManyField(related_name='sponsors', to='pages.seasonbadge'),
        ),
        migrations.RunPython(add_season_badges)
    ]
