# Generated by Django 4.2.3 on 2024-02-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_appinfo_seasonbadge_sponsor_season_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
