# Generated by Django 3.2.14 on 2023-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
